### ISSUE TITLE
Noto Sans Takri: Sample text is missing on https://fonts.google.com/

### ISSUE THREAD

**Issue by eliheuer** [notofonts/takri#16]
NotoSansTakri-Regular.ttf Version 2.004 cc @simoncozens 

### OS name and version
  > MacOS 13.1

### Application name and version
  > Chrome 115.0.5790.170

### Issue
On https://fonts.google.com/, Noto Sans Takri sample text is missing.

### Screenshot
<img width="1920" alt="Screenshot 2023-08-25 at 6 40 27 AM" src="https://github.com/notofonts/takri/assets/5162664/b0e173d2-289d-4d7c-a500-64cfaf2e91ba">

**Comment by simoncozens** [comment]
Thanks. Not a bug in the font, though. :-) I think we added Takri to the lang repo recently but maybe it's not gone through the pipeline yet.

**Comment by simoncozens** [comment]
Yeah, everything looks good from the Google/fonts end too: we have doi_Takr sample and the font has that language declared in the METADATA.pb. Maybe it needs repushing? Anyway, nothing to do here.
