### ISSUE TITLE
TAKRI word for NGA+AA and TA+AA+ANUSVARA looks the same.

### ISSUE THREAD

**Issue by nik9hil** [notofonts/takri#2]
### Font 
NotoSansTakri-Regular.otf
  
### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansTakriNotoSansTakri-Regular.otf
 
Date: 2020-07-12

### Font Version
 Version 2.001

### Issue
TAKRI word for NGA+AA and TA+AA+ANUSVARA looks the same. To correct it, shift AA in NGA+AA on the right of the dot of TAKRI LETTER NGA.

### Character data
Image 1
U+11699 TAKRI LETTER TA   𑚙 
U+116AD TAKRI VOWEL SIGN AA   𑚭
U+116AB TAKRI SIGN ANUSVARA  𑚫

Image 2
U+1168E TAKRI LETTER NGA   𑚎 
U+116AD TAKRI VOWEL SIGN AA    𑚭
 
### Screenshot
![image](https://user-images.githubusercontent.com/32241740/87242718-c59a3e00-c44c-11ea-8754-3b7aa4c0dac4.png)
![image](https://user-images.githubusercontent.com/32241740/87242706-b3200480-c44c-11ea-8785-28abd0a6a51a.png)

**Comment by simoncozens** [comment]
Fixed it. This is how it looks now:

![shape](https://user-images.githubusercontent.com/106728/189645491-3af5abcd-07c0-4a7a-88c6-98e0fc9b2da1.png)
